--------------------------------- Manual Seeding --------------------------
INSERT INTO ListingCity VALUES('clodun45p0000puvv2k02jp9v','Calgary','Alberta','calgary--alberta');
INSERT INTO ListingCity VALUES('clodun45q0001puvvudsjackm','Edmonton','Alberta','edmonton--alberta');
INSERT INTO ListingCity VALUES('clodun45s0002puvv58n0tf52','Kelowna','British Columbia','kelowna--british-columbia');
INSERT INTO ListingCity VALUES('clodun45t0003puvvr6g51zzi','Winnipeg','Manitoba','winnipeg--manitoba');
INSERT INTO ListingCity VALUES('clodun45u0004puvv0i49jz6b','Fort McMurray','Alberta','fort-mcmurray--alberta');
INSERT INTO ListingCity VALUES('clodun45v0005puvvy5or883f','Brandon','Manitoba','brandon--manitoba');
INSERT INTO ListingCity VALUES('clodun45w0006puvv59lis2gs','Red Deer','Alberta','red-deer--alberta');
INSERT INTO ListingCity VALUES('clodun45x0007puvv7jjia9he','Victoria','British Columbia','victoria--british-columbia');
INSERT INTO ListingCity VALUES('clodun45y0008puvv525bt6qh','Fredericton','New Brunswick','fredericton--new-brunswick');
INSERT INTO ListingCity VALUES('clodun45z0009puvvhoe0oswy','Lethbridge','Alberta','lethbridge--alberta');
INSERT INTO ListingCity VALUES('clodun460000apuvvt338vzlm','Vancouver','British Columbia','vancouver--british-columbia');
INSERT INTO ListingCity VALUES('clodun461000bpuvvb280fzqe','Miramichi','New Brunswick','miramichi--new-brunswick');
INSERT INTO ListingCity VALUES('clodun462000cpuvvfat9yprd','Burnaby','British Columbia','burnaby--british-columbia');
INSERT INTO ListingCity VALUES('clodun463000dpuvvh65vxkx2','Thompson','Manitoba','thompson--manitoba');
INSERT INTO ListingCity VALUES('clodun464000epuvvjzal0git','Corner Brook','Newfoundland and Labrador','corner-brook--newfoundland-and labrador');
INSERT INTO ListingCity VALUES('clodun465000fpuvvp744cc0h','St. John''s','Newfoundland and Labrador','st.-john''s--newfoundland-and labrador');
INSERT INTO ListingCity VALUES('clodun466000gpuvv6btli89d','Sydney','Nova Scotia','sydney--nova-scotia');
INSERT INTO ListingCity VALUES('clodun467000hpuvvcjzujtls','Mount Pearl','Newfoundland and Labrador','mount-pearl--newfoundland-and labrador');
INSERT INTO ListingCity VALUES('clodun468000ipuvvndmzzsx5','Surrey','British Columbia','surrey--british-columbia');
INSERT INTO ListingCity VALUES('clodun469000jpuvv4eivd094','Truro','Nova Scotia','truro--nova-scotia');
INSERT INTO ListingCity VALUES('clodun46a000kpuvvdjaj45ox','Selkirk','Manitoba','selkirk--manitoba');
INSERT INTO ListingCity VALUES('clodun46b000lpuvvxv0iiywe','Grand Falls-Windsor','Newfoundland and Labrador','grand-falls-windsor--newfoundland-and labrador');
INSERT INTO ListingCity VALUES('clodun46c000mpuvv3wn2qp9c','Ottawa','Ontario','ottawa--ontario');
INSERT INTO ListingCity VALUES('clodun46d000npuvvsyv5ak3o','Toronto','Ontario','toronto--ontario');
INSERT INTO ListingCity VALUES('clodun46e000opuvvyuywksqz','Hamilton','Ontario','hamilton--ontario');
INSERT INTO ListingCity VALUES('clodun46f000ppuvvp0drvhgw','Mississauga','Ontario','mississauga--ontario');
INSERT INTO ListingCity VALUES('clodun46g000qpuvvdp5entv2','Halifax','Nova Scotia','halifax--nova-scotia');
INSERT INTO ListingCity VALUES('clodun46h000rpuvvmw54hwg1','Stratford','Prince Edward Island','stratford--prince-edward island');
INSERT INTO ListingCity VALUES('clodun46i000spuvvwdyzzzox','Saint John','New Brunswick','saint-john--new-brunswick');
INSERT INTO ListingCity VALUES('clodun46j000tpuvv1h79chwp','Brampton','Ontario','brampton--ontario');
INSERT INTO ListingCity VALUES('clodun46k000upuvvoj6dmxdq','Cornwall','Prince Edward Island','cornwall--prince-edward island');
INSERT INTO ListingCity VALUES('clodun46l000vpuvvogfb5tdx','Dartmouth','Nova Scotia','dartmouth--nova-scotia');
INSERT INTO ListingCity VALUES('clodun46m000wpuvvp5cnqfx1','Charlottetown','Prince Edward Island','charlottetown--prince-edward island');
INSERT INTO ListingCity VALUES('clodun46n000xpuvvl7xfxa08','Quebec City','Quebec','quebec-city--quebec');
INSERT INTO ListingCity VALUES('clodun46o000ypuvvxpmd0ioa','Montreal','Quebec','montreal--quebec');
INSERT INTO ListingCity VALUES('clodun46p000zpuvvqms1hiix','Moncton','New Brunswick','moncton--new-brunswick');
INSERT INTO ListingCity VALUES('clodun46q0010puvvt07oku7a','Laval','Quebec','laval--quebec');
INSERT INTO ListingCity VALUES('clodun46r0011puvvvzelfvxv','Regina','Saskatchewan','regina--saskatchewan');
INSERT INTO ListingCity VALUES('clodun46s0012puvv3iss1x38','Gatineau','Quebec','gatineau--quebec');
INSERT INTO ListingCity VALUES('clodun46u0013puvvrhy71uw7','Summerside','Prince Edward Island','summerside--prince-edward island');
INSERT INTO ListingCity VALUES('clodun46v0014puvvik0qy842','Swift Current','Saskatchewan','swift-current--saskatchewan');
INSERT INTO ListingCity VALUES('clodun46w0015puvv1bu4faql','Saskatoon','Saskatchewan','saskatoon--saskatchewan');
INSERT INTO ListingCity VALUES('clodun46x0016puvvieboe7il','Prince Albert','Saskatchewan','prince-albert--saskatchewan');
INSERT INTO ListingCity VALUES('clodun46y0017puvv9t9vsr8o','Sherbrooke','Quebec','sherbrooke--quebec');
INSERT INTO ListingCity VALUES('clodun46z0018puvvb450elym','Yellowknife','Northwest Territories','yellowknife--northwest-territories');
INSERT INTO ListingCity VALUES('clodun4700019puvvgki8mk40','Inuvik','Northwest Territories','inuvik--northwest-territories');
INSERT INTO ListingCity VALUES('clodun471001apuvvg8jlqgu5','Hay River','Northwest Territories','hay-river--northwest-territories');
INSERT INTO ListingCity VALUES('clodun472001bpuvvqiiyv3ef','Iqaluit','Nunavut','iqaluit--nunavut');
INSERT INTO ListingCity VALUES('clodun472001cpuvvi12qql5g','Rankin Inlet','Nunavut','rankin-inlet--nunavut');
INSERT INTO ListingCity VALUES('clodun473001dpuvv228mhv2k','Fort Smith','Northwest Territories','fort-smith--northwest-territories');
INSERT INTO ListingCity VALUES('clodun474001epuvvc4svq7gh','Moose Jaw','Saskatchewan','moose-jaw--saskatchewan');
INSERT INTO ListingCity VALUES('clodun475001fpuvvyttqvg59','Whitehorse','Yukon','whitehorse--yukon');
INSERT INTO ListingCity VALUES('clodun476001gpuvv4hfw8tos','Baker Lake','Nunavut','baker-lake--nunavut');
INSERT INTO ListingCity VALUES('clodun477001hpuvvyvconkr4','Arviat','Nunavut','arviat--nunavut');
INSERT INTO ListingCity VALUES('clodun478001ipuvvhabknxsf','Carcross','Yukon','carcross--yukon');
INSERT INTO ListingCity VALUES('clodun47a001jpuvv7nymba92','Dawson City','Yukon','dawson-city--yukon');
INSERT INTO ListingCity VALUES('clodun47b001kpuvv9c1efy59','Watson Lake','Yukon','watson-lake--yukon');